<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Messenger.Bootstrap</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Messenger.Data\Messenger.Data.csproj" />
    <ProjectReference Include="..\..\src\Messenger.Licensing\Messenger.Licensing.csproj" />
  </ItemGroup>

</Project>
